import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Home/Header";
import Footer from "./Home/Footer";
import ScrollToTop from "./Home/Top";
import SupportButton from "./Home/Support";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "MShop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <ScrollToTop/>
        <SupportButton/>
        <Footer/>
      </body>
    </html>
  );
}
